/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.registradora;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author David
 */
public class Caja_principal extends javax.swing.JFrame {

    String producto,itemfactu;
    int jugo=0,cafe=0,leche=0,pan=0,cereal=0,compra=0,tomate=0,manzana=0,lechuga=0,naranja=0,maiz=0,aceite=0,coca=0,arroz=0,ketchup=0,queso=0,cepillo=0,copitos=0,alcohol=0,colgate=0,papel=0;
    JButton boton;
    ImageIcon imagen;
    Icon Icono;
    
    public Caja_principal() {
        initComponents();
        /*
        this.botonjugo.setVisible(false);
        this.botoncafe.setVisible(false);
        this.botonleche.setVisible(false);
        this.botonpan.setVisible(false);
        this.botoncereal.setVisible(false);
        this.botontomate.setVisible(false);
        this.botonmanzana.setVisible(false);
        this.botonlechuga.setVisible(false);
        this.botonnaranja.setVisible(false);
        this.botonmaiz.setVisible(false);
        this.botonaceite.setVisible(false);
        this.botoncoca.setVisible(false);
        this.botonarroz.setVisible(false);
        this.botonqueso.setVisible(false);
        this.botonketchup.setVisible(false);
        this.botoncepillo.setVisible(false);
        this.botonalcohol.setVisible(false);
        this.botoncolgate.setVisible(false);
        this.botonpapel.setVisible(false);
        this.botoncopitos.setVisible(false);
        this.botonvacio.setVisible(true);
        
        */

    }
public void productos (){
    /*
        this.botonjugo.setVisible(false);
        this.botoncafe.setVisible(false);
        this.botonleche.setVisible(false);
        this.botonpan.setVisible(false);
        this.botoncereal.setVisible(false);
        this.botontomate.setVisible(false);
        this.botonmanzana.setVisible(false);
        this.botonlechuga.setVisible(false);
        this.botonnaranja.setVisible(false);
        this.botonmaiz.setVisible(false);
        this.botonaceite.setVisible(false);
        this.botoncoca.setVisible(false);
        this.botonarroz.setVisible(false);
        this.botonqueso.setVisible(false);
        this.botonketchup.setVisible(false);
        this.botoncepillo.setVisible(false);
        this.botonalcohol.setVisible(false);
        this.botoncolgate.setVisible(false);
        this.botonpapel.setVisible(false);
        this.botoncopitos.setVisible(false);
        this.botonvacio.setVisible(false);
       */
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        boton3 = new javax.swing.JButton();
        botonvisualizar = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        precio = new javax.swing.JTextField();
        botoningresar = new javax.swing.JButton();
        mostrar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        factu = new javax.swing.JTextArea();
        jTextField6 = new javax.swing.JTextField();
        preciofinal = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        getContentPane().add(boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 50, 50));

        botonvisualizar.setBackground(new java.awt.Color(51, 255, 204));
        botonvisualizar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonvisualizar.setText("Visualizar");
        botonvisualizar.setToolTipText("");
        botonvisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonvisualizarActionPerformed(evt);
            }
        });
        getContentPane().add(botonvisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 160, 60));

        boton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        getContentPane().add(boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 50, 50));

        boton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        getContentPane().add(boton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 50, 50));

        boton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        getContentPane().add(boton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 50, 50));

        boton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });
        getContentPane().add(boton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 50, 50));

        boton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });
        getContentPane().add(boton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 50, 50));

        boton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        boton7.setText("7");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });
        getContentPane().add(boton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 50, 50));

        boton0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });
        getContentPane().add(boton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 50, 50));

        boton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        boton8.setText("8");
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });
        getContentPane().add(boton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 50, 50));

        boton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        getContentPane().add(boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 50, 50));

        precio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        precio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 290, 40));

        botoningresar.setBackground(new java.awt.Color(51, 255, 51));
        botoningresar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botoningresar.setText("Ingresar");
        botoningresar.setToolTipText("");
        botoningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoningresarActionPerformed(evt);
            }
        });
        getContentPane().add(botoningresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 220, 50));

        mostrar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 190, 50));

        factu.setColumns(20);
        factu.setRows(5);
        jScrollPane1.setViewportView(factu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 300, 470));

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField6.setText("-----------------T I R I L L A    D E    C O M P R A ---------------");
        jTextField6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 300, 40));

        preciofinal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        preciofinal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(preciofinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, 300, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void reinicio (){
jugo=0;
cafe=0;
leche=0;
pan=0;
cereal=0;
compra=0;
tomate=0;
manzana=0;
lechuga=0;
naranja=0;
maiz=0;
aceite=0;
coca=0;
arroz=0;
ketchup=0;
queso=0;
cepillo=0;
copitos=0;
alcohol=0;
colgate=0;
papel=0;
}
    private void botonvisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonvisualizarActionPerformed
    producto = mostrar.getText();
    
if(producto.length()<=0){mostrar.setText("->Ingrese un producto<-");}
if(producto.contains("1101")){
   productos();
   //this.botonjugo.setVisible(true);
   precio.setText("->JUGO --> $50");
        }
if(producto.contains("1102")){
   productos();
   //this.botoncafe.setVisible(true);
   precio.setText("->CAFE --> $72");
        }
if(producto.contains("1103")){
   productos();
   //this.botonleche.setVisible(true);
   precio.setText("->lECHE --> $30");
        }
if(producto.contains("1104")){
   productos();
   //this.botonpan.setVisible(true);
   precio.setText("->P A N --> $90");
        }
if(producto.contains("1105")){
   productos();
   //this.botoncereal.setVisible(true);
   precio.setText("->C E R E A L--> $101");
         }





if(producto.contains("2206")){
   productos();
   //this.botontomate.setVisible(true);
   precio.setText("->TOMATE --> $80");
        }
if(producto.contains("2207")){
   productos();
   //this.botonmanzana.setVisible(true);
   precio.setText("->MANZANA --> $72");
        }
if(producto.contains("2208")){
   productos();
   //this.botonlechuga.setVisible(true);
   precio.setText("->LECHEUGA --> $76");
        }
if(producto.contains("2209")){
   productos();
   //this.botonnaranja.setVisible(true);
   precio.setText("->NARANJA --> $90");
        }
if(producto.contains("2210")){
   productos();
   //this.botonmaiz.setVisible(true);
   precio.setText("->M A I Z --> $52");
         }
   




if(producto.contains("3311")){
   productos();
   //this.botonaceite.setVisible(true);
   precio.setText("->ACEITE --> $110");
        }
if(producto.contains("3312")){
   productos();
   //this.botoncoca.setVisible(true);
   precio.setText("->COCA - COLA --> $86");
        }
if(producto.contains("3313")){
   productos();
   //this.botonarroz.setVisible(true);
   precio.setText("->ARROZ --> $15");
        }
if(producto.contains("3314")){
   productos();
   //this.botonketchup.setVisible(true);
   precio.setText("->K E T C H U P --> $120");
        }
if(producto.contains("3315")){
   productos();
   //this.botonqueso.setVisible(true);
   precio.setText("->Q U E S O--> $150");
         }





if(producto.contains("4416")){
   productos();
   //this.botoncepillo.setVisible(true);
   precio.setText("->CEPILLO --> $100");
        }
if(producto.contains("4417")){
   productos();
   //this.botoncopitos.setVisible(true);
   precio.setText("->COPITOS --> $210");
        }
if(producto.contains("4418")){
   productos();
   //this.botonalcohol.setVisible(true);
   precio.setText("->ALCOHOL --> $300");
        }
if(producto.contains("4419")){
   productos();
   //this.botoncolgate.setVisible(true);
   precio.setText("->C O L G A T E--> $102");
        }
if(producto.contains("4420")){
   productos();
   //this.botonpapel.setVisible(true);
   precio.setText("->PAPEL HIGIENICO --> $400");
         }
   
    }//GEN-LAST:event_botonvisualizarActionPerformed

    
    

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
mostrar.setText(mostrar.getText()+"1");
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
mostrar.setText(mostrar.getText()+"2");
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
mostrar.setText(mostrar.getText()+"3");        // TODO add your handling code here:
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
mostrar.setText(mostrar.getText()+"4"); 
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
mostrar.setText(mostrar.getText()+"5"); 
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
mostrar.setText(mostrar.getText()+"6"); 
    }//GEN-LAST:event_boton6ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
mostrar.setText(mostrar.getText()+"7"); 
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
mostrar.setText(mostrar.getText()+"8"); 
    }//GEN-LAST:event_boton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
mostrar.setText(mostrar.getText()+"9"); 
    }//GEN-LAST:event_boton9ActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
mostrar.setText(mostrar.getText()+"0"); 
    }//GEN-LAST:event_boton0ActionPerformed

    private void botoningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoningresarActionPerformed
    producto = mostrar.getText();
    
    if(producto.contains("1101")){
    factu.setText(factu.getText()+("\n----> P R O D U C T O -- J U G O  ----> $50" ));
    mostrar.setText("");
    jugo = jugo +1;
    }  
    if(producto.contains("1102")){
    factu.setText(factu.getText()+("\n----> P R O D U C T O -- C A F E  ----> $72" ));
    mostrar.setText("");
    cafe = cafe +1;
    }  
    if(producto.contains("1103")){
    factu.setText(factu.getText()+("\n----> P R O D U C T O -- L E C H E  ----> $30" ));
    mostrar.setText("");
    leche = leche +1;
    }  
    if(producto.contains("1104")){
    factu.setText(factu.getText()+("\n----> P R O D U C T O -- P A N  ----> $90" ));
    mostrar.setText("");
    pan = pan +1;
    }
    if(producto.contains("1105")){
    factu.setText(factu.getText()+("\n----> P R O D U C T O -- C E R E A L  ----> $101" ));
    mostrar.setText("");
    cereal = cereal +1;
    } 
    
    
    
    
    
    if(producto.contains("2206")){
    factu.setText(factu.getText()+("\n----> P R O D U C T O --T O M A T E---> $80" ));
    mostrar.setText("");
    tomate = tomate +1;
    }  
    if(producto.contains("2207")){
    factu.setText(factu.getText()+("\n----> P R O D U C T O --M A N Z A N A---> $72" ));
    mostrar.setText("");
    manzana = manzana +1;
    }  
    if(producto.contains("2208")){
    factu.setText(factu.getText()+("\n----> P R O D U C T O --L E C H U G A----> $76" ));
    mostrar.setText("");
    lechuga = lechuga +1;
    }  
    if(producto.contains("2209")){
    factu.setText(factu.getText()+("\n----> P R O D U C T O --N A R A N J A ---> $90" ));
    mostrar.setText("");
    naranja = naranja +1;
    }
    if(producto.contains("2210")){
    factu.setText(factu.getText()+("\n----> P R O D U C T O -- M A I Z ----> 52" ));
    mostrar.setText("");
    maiz = maiz +1;
    } 
    
    
    
    
    if(producto.contains("3311")){
    factu.setText(factu.getText()+("\n----> P R O D U C T O -- A C E I T E---->$110" ));
    mostrar.setText("");
    aceite = aceite +1;
    }  
    if(producto.contains("3312")){
    factu.setText(factu.getText()+("\n----> P R O D U C T O -- COCA COLA ----> $86" ));
    mostrar.setText("");
    coca = coca +1;
    }  
    if(producto.contains("3313")){
    factu.setText(factu.getText()+("\n----> P R O D U C T O -- A R R O Z  ----> $15" ));
    mostrar.setText("");
    arroz = arroz +1;
    }  
    if(producto.contains("3314")){
    factu.setText(factu.getText()+("\n----> P R O D U C T O -- K E T C H U P----> $120" ));
    mostrar.setText("");
    ketchup = ketchup +1;
    }
    if(producto.contains("3315")){
    factu.setText(factu.getText()+("\n----> P R O D U C T O --Q U E S O ----> $150" ));
    mostrar.setText("");
    queso = queso +1;
    } 
    
    
    
    
    
    if(producto.contains("4416")){
    factu.setText(factu.getText()+("\n----> P R O D U C T O --C E P I L L O---> $100" ));
    mostrar.setText("");
    cepillo = cepillo +1;
    }  
    if(producto.contains("4417")){
    factu.setText(factu.getText()+("\n----> P R O D U C T O --C O P I T O S---> $210" ));
    mostrar.setText("");
    copitos = copitos +1;
    }  
    if(producto.contains("4418")){
    factu.setText(factu.getText()+("\n----> P R O D U C T O --A L C O H O L----> $300" ));
    mostrar.setText("");
    alcohol = alcohol +1;
    }  
    if(producto.contains("4419")){
    factu.setText(factu.getText()+("\n----> P R O D U C T O --C O L G A T E---> $102" ));
    mostrar.setText("");
    colgate = colgate +1;
    }
    if(producto.contains("4420")){
    factu.setText(factu.getText()+("\n----> P R O D U C T O -- P A P E L ----> 52" ));
    mostrar.setText("");
    papel = papel +1;
    }
    
    
    }//GEN-LAST:event_botoningresarActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caja_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caja_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caja_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caja_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Caja_principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botoningresar;
    private javax.swing.JButton botonvisualizar;
    private javax.swing.JTextArea factu;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField mostrar;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField preciofinal;
    // End of variables declaration//GEN-END:variables
}
